apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdotnet-d-app-deployment 
  labels:
    app: newdotnet-d-app
  namespace: deeksha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newdotnet-d-app
  template:
    metadata:
      labels:
        app: newdotnet-d-app
    spec:
      containers:
<<<<<<< HEAD
      - name: newdotnet-d-app
        image: deekshamaddineni/dee
        ports:
        - containerPort: 5000
=======
      - name: dockerdep-10-app
        image: bhanuteja822/bhanu
        ports:
        - containerPort: 80
>>>>>>> 3cedcb7ba0a13d898583cf201b0d75cb89daaf7a
