version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_URLS=http://*:5000
    depends_on:
      - redis
      - mysql

  redis:
    image: redis
    ports:
      - "6378:6378"

  mysql:
    image: mysql:8.0
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database